animals_url: "http://localhost:3123/animals/v1/animals"
home_url: "http://localhost:3123/animals/v1/home"

batch_size: 100

# Retry & Timeout settings
max_attempts: 5
backoff_factor: 2
timeout_seconds: 30
